/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "secondary": "#89ceff",
        "inverse-primary": "#00668a",
        "on-primary-container": "#004965",
        "on-surface-variant": "#bdc8d1",
        "outline-variant": "#3e484f",
        "tertiary-container": "#a3abff",
        "on-secondary-container": "#00344e",
        "surface-container-lowest": "#060e20",
        "on-primary": "#00354a",
        "primary-container": "#38bdf8",
        "tertiary-fixed": "#e0e0ff",
        "surface-container-highest": "#2d3449",
        "error-container": "#93000a",
        "on-surface": "#dae2fd",
        "background": "#0b1326",
        "surface": "#0b1326",
        "on-secondary": "#00344d",
        "on-tertiary": "#131e8c",
        "on-tertiary-container": "#2c37a0",
        "inverse-on-surface": "#283044",
        "surface-bright": "#31394d",
        "on-secondary-fixed": "#001e2f",
        "on-primary-fixed-variant": "#004c69",
        "tertiary-fixed-dim": "#bdc2ff",
        "on-secondary-fixed-variant": "#004c6e",
        "surface-container": "#171f33",
        "secondary-fixed-dim": "#89ceff",
        "on-tertiary-fixed-variant": "#2f3aa3",
        "surface-dim": "#0b1326",
        "outline": "#87929a",
        "secondary-fixed": "#c9e6ff",
        "primary": "#8ed5ff",
        "surface-container-high": "#222a3d",
        "surface-container-low": "#131b2e",
        "inverse-surface": "#dae2fd",
        "on-tertiary-fixed": "#000767",
        "primary-fixed-dim": "#7bd0ff",
        "error": "#ffb4ab",
        "surface-variant": "#2d3449",
        "surface-tint": "#7bd0ff",
        "secondary-container": "#00a2e6",
        "on-background": "#dae2fd",
        "on-primary-fixed": "#001e2c",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "tertiary": "#c5c9ff",
        "primary-fixed": "#c4e7ff"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "sidebar-width": "16rem",
        "space-xs": "0.5rem",
        "space-2xs": "0.25rem",
        "space-3xl": "4rem",
        "max-content-width": "80rem",
        "gutter-mobile": "1rem",
        "space-2xl": "3rem",
        "gutter-desktop": "1.5rem",
        "space-sm": "0.75rem",
        "space-xl": "2rem"
      },
      "fontFamily": {
        "headline-xl": ["Inter"],
        "headline-lg": ["Inter"],
        "body-base": ["Inter"],
        "metric-val": ["JetBrains Mono"],
        "display-hero-mobile": ["Inter"],
        "body-lg": ["Inter"],
        "code-badge": ["JetBrains Mono"],
        "display-hero": ["Inter"],
        "headline-sm": ["Inter"],
        "body-sm": ["Inter"],
        "code-sm": ["JetBrains Mono"]
      },
      "fontSize": {
        "headline-xl": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "body-base": ["14px", { "lineHeight": "22px", "fontWeight": "400" }],
        "metric-val": ["28px", { "lineHeight": "34px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "display-hero-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "26px", "fontWeight": "400" }],
        "code-badge": ["12px", { "lineHeight": "16px", "letterSpacing": "0em", "fontWeight": "500" }],
        "display-hero": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.03em", "fontWeight": "700" }],
        "headline-sm": ["18px", { "lineHeight": "26px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-sm": ["12px", { "lineHeight": "18px", "fontWeight": "400" }],
        "code-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
